input←
x←⍳9
newfish←fish←(9⍴0)
{A←⍺ ⋄ B←(+/A⍷input) ⋄ fish[A+1]←B}/x
⎕FR←1287
⎕PP←20
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
newfish←1⌽fish ⋄ newfish[7]←fish[8]+fish[1] ⋄ fish←newfish
+/fish
